import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-screen from-blue-500/60 to-slate-300/60 bg-gradient-to-tr` }>
        <div className="  h-full backdrop-blur-4">
          {children}
        </div>
      </body>
    </html>
  );
}
